set-option -g status-style "bg=#0f1219,fg=#83a9c0"
set-option -g window-status-current-style "fg=#fad253"
set-option -g window-status-style "fg=#e9543a"
set-option -g status-left-style "fg=#749172"
set-option -g status-left-length 30
set-option -g status-right '#[fg=white]%H:%M %A,%d %B %Y'

# vim: ft=tmux
