unbind C-b
set -g prefix M-a
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded ~/.tmux.conf"
#set -g default-terminal "tmux-256color"
#set -ag terminal-overrides ",xterm-256color:RGB"
set -g mouse on
set -g base-index 1
set -sg escape-time 0
set-window-option -g pane-base-index 1
setw -g mode-keys vi

# easier navigation
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
bind -n M-p previous-window
bind -n M-n next-window

# better splits
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# status bar
set-option -g status-position top

# Vi copy mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel
source-file ~/.config/tmux/colorscheme.conf
